[package]
name = "auspice-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ap"
path = "src/ap/main.rs"

[[bin]]
name = "apc"
path = "src/apc/main.rs"

[dependencies]
auspice-checker = { version = "0.1.0", path = "../checker" }
auspice-codegen = { version = "0.1.0", path = "../codegen" }
auspice-core = { version = "0.1.0", path = "../core" }
auspice-ir = { version = "0.1.0", path = "../ir" }
auspice-stream = { version = "0.1.0", path = "../stream" }
auspice-syntax = { version = "0.1.0", path = "../syntax" }
auspice-universe = { version = "0.1.0", path = "../universe" }
clap = { version = "4.6.6", features = ["derive"] }
